### PR TITLE
Scapy's automotive module

### PR DESCRIPTION
**Pull request by gpotter2**
Hi,
Scapy has an automotive module, and capabilities to send/receive on CAN, ISOTP... It's used for instance in this talk: https://scapy.net/conf/troopers2019 . I thought it would be cool to have.
Have a good day

### CODE REVIEW

**Comment by gpotter2** [comment]
I missed

> The body of your commit message should contain a link to the repository.

**Comment by jaredthecoder** [comment]
LGTM. Merging.

**Comment by jaredthecoder** [comment]
Also, @gpotter2, I'm honored you made a PR. Just realized you're a Scapy maintainer and not simply submitting it. Amazing library, and I appreciate you sending this PR. I use Scapy occasionally for packet manipulation, but because this repo was more for me to stay up to date with CAN stuff and not actually doing it, I didn't realize Scapy had that module. Thanks again for your efforts!

**Comment by gpotter2** [comment]
Thanks for the kind words 🙂

**Pull request merged**
